### PR TITLE
Clarify 'case 2' for 'this' explanation.

### PR DESCRIPTION
**Pull request by kennyklee**
Here is something I learned today.  See example below.

```
var obj = {
  hello: function() { return "hello, " + this.username; },
  username: "Kenny"
};
obj.hello(); // "hello, Kenny

var obj2 = {
  hello: obj.hello,
  username: "Gordon"
};
obj2. hello(); // "hello, Gordon"
```

Rather than saying 'contains' the method, 'calls' the method seems more accurate.

### CODE REVIEW

**Comment by kennyklee** [comment]
I also learned that the object that 'calls the method' is a 'receiver'.  I don't think it's worth getting into the vocab...but just found it interesting for my own leveling-up. :)

http://d.weblife.us/Lmyx

**Comment by gordonmzhu** [comment]
I think call is actually more confusing.

Contains is still accurate in your example. When you call `obj2.hello`,  the `.hello` method belongs to `obj2`. Or to use my wording, `obj2` contains `obj2.hello` and therefore `this.username` should be `"Gordon"`.

**Comment by gordonmzhu** [comment]
@kennyklee I could also be even more explicit and say, `this` will be whatever is to the left of the `.`. So for example when you run `myObject.myMethod();`, `myObject` is on the left side of `.`. 

Thoughts?

**Comment by gordonmzhu** [comment]
@kennyklee "Left of the dot" rule

**Comment by gordonmzhu** [comment]
@kennyklee That's kinda memorable.

**Comment by kennyklee** [comment]
@gordonmzhu I see your point.  I like the 'left of dot' visual, as long as students understand the bracket notation as well. `myObject["myMethod"]()`

**Comment by gordonmzhu** [comment]
Closed with https://github.com/gordonmzhu/cheatsheet-js/commit/ba549cabe8b40b1f62c338520eb8d79b5ded75d1

**Pull request closed without merging**
